### ISSUE TITLE
XDM not able to draw interface after reopening when this extension is enabled

### ISSUE THREAD

**Issue by HritwikSinghal** [Selenium-H/Animation-Tweaks#39]
**Describe the bug**

**On Manjaro Wayland 20.2, also happened on ubuntu 20.04 wayland. DID NOT TEST ON XORG**

I install XDM, i open XDM, i close it by clicking the 'X' on top menu bar. **I again open XDM and it does not open**. It shows that one window is open in dash and overview but that window has no interface. see the screenshots

**To Reproduce**
1. Install XDM . open xdm (from all apps). It opens fine. I close it by clicking on "X" on top bar.
2. I again open it from 'all apps' or 'dash' but this time this bug happens.

**Expected behavior**
XDM should open normally.

**Screenshots**

![Screenshot from 2021-02-08 02-39-54](https://user-images.githubusercontent.com/29531474/107159575-07756d80-69b7-11eb-9dad-4826a9b3ad01.png)

**please complete the following information:**
 - OS: Manjaro Nibia 20.2
 - Animation Tweaks Version: Latest as of Feb 8, 2021. 12.01

**Generated log using below method**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

```sh
$ /opt/xdman  jre/bin/java -jar xdman.jar

[ main ] loading...
[ main ] 11.0.6 5.10.7-3-MANJARO
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
en
[ main ] Loading language en
[ main ] Context initialized
[ Thread-4 ] instance starting...
[ Thread-4 ] instance started.
[ AWT-EventQueue-0 ] showing main window.
[ Thread-4 ] Lock acquired...
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/icon.png
Error setting Dock icon
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/bg_nav.png
[ AWT-EventQueue-0 ] List changed
[ AWT-EventQueue-0 ] SystemTray is not supported
checking for app update
[ Thread-3 ] manifest download response: 200
7.2.11 7.2.11
New session
New session
New session                                                         # I closed XDM here and reopened it.
[ Thread-7 ] Response set
[ Thread-7 ] java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at xdman.util.NetUtils.readLine(NetUtils.java:16)
	at xdman.monitoring.Request.read(Request.java:16)
	at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:485)
	at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
	at java.base/java.lang.Thread.run(Unknown Source)
New session                                                                 # closed and reopened again
[ Thread-8 ] Response set
[ Thread-8 ] java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at xdman.util.NetUtils.readLine(NetUtils.java:16)
	at xdman.monitoring.Request.read(Request.java:16)
	at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:485)
	at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
	at java.base/java.lang.Thread.run(Unknown Source)
New session
```

**Additional Info**

- **This does not happen when i disable "Animation Tweaks" Gnome Shell Extension.**
- Adding XDM to Application Profiles and disabling all effects for it Does not work. 
- This issue disappears if i disable closing effects for all "normal Windows". Like
![image](https://user-images.githubusercontent.com/29531474/107160232-ffb7c800-69ba-11eb-9e8d-64a4d668a4ac.png)

- [Here](https://github.com/subhra74/xdm/issues/484) is issue on XDM GH page

**Comment by Selenium-H** [comment]
I tried xdm on arch, however the above issue appeared only once and was gone after closing xdm and rebooting.
Could you please let me know the preferences under which it's happening? Also try disabling focusing and defocusing effects if that's enabled.

**Comment by HritwikSinghal** [comment]
Focus effects are disabled. But after restart did this issue occur for you? since if we kill the app by 'kill -9' command or by restarting the PC, the issue will disappear, but as soon as you open xdm and close it again, it will re-appear.

**Comment by Selenium-H** [comment]
> I tried xdm on arch, however the above issue appeared only once and was gone after closing xdm and rebooting.

Sorry. I was logging to xorg previously . 
I was able to reproduce this issue on wayland. I'll update once a workaround is found.

**Comment by Selenium-H** [comment]
Please try adding `xdm` to profiles list. With `dconf-Editor` navigate to `org/gnome/shell/extensions/animation-tweaks/`. In key `name-list` replace `Xtreme Download Manager` with `xdman-Main`. Apply the changes.
Open `Animation Tweaks` extension preferences and in `Profiles` tab select `xdman-Main` and turn off `close` status switch. Enable `Application Profiles` switch. Enable `Closing Effects [ for windows ]` switch from `Actions` tab.

![Image](https://user-images.githubusercontent.com/46006930/107980106-b3d1d800-6fe5-11eb-91e3-8bfe6f7e4515.png)


This will prevent closing animation for xdm.

**Comment by HritwikSinghal** [comment]
> Please try adding `xdm` to profiles list. With `dconf-Editor` navigate to `org/gnome/shell/extensions/animation-tweaks/`. In key `name-list` replace `Xtreme Download Manager` with `xdman-Main`. Apply the changes.
> Open `Animation Tweaks` extension preferences and in `Profiles` tab select `xdman-Main` and turn off `close` status switch. Enable `Application Profiles` switch. Enable `Closing Effects [ for windows ]` switch from `Actions` tab.

Thanks, this works! But isn't this just a temporary solution? i mean this bug should affect java applications if it affects xdm (xdm is java app).

**Comment by Selenium-H** [comment]
> But isn't this just a temporary solution?

Yes.

> this bug should affect java applications if it affects xdm

I'm not sure if all java applications are affected. Some of the applications (even native ones) also have this type of issues while others work fine.

**Comment by auipga** [comment]
`phpstorm` with its own `aur/phpststorm-jre` isn't affected on Archlinux, Gnome 40.2, extension v14
